### ISSUE TITLE
play pause function

### ISSUE THREAD

**Issue by AmanBisht01** [FABhishek/WatchPawrii#1]
The play pause function is not working.
They should be in sync

**Comment by neetra** [comment]
I am interested

**Comment by Jyo561** [comment]
I am interested

**Comment by AmanBisht01** [comment]
> I am interested
> 

Go ahead

**Comment by AmanBisht01** [comment]
@neetra go ahead

**Comment by AmanBisht01** [comment]
@neetra any update ??
