### ISSUE TITLE
Add chat facility in rooms 

### ISSUE THREAD

**Issue by AmanBisht01** [FABhishek/WatchPawrii#2]
Add chat facility but it should be only specific to particular rooms.

**Comment by lokita282** [comment]
Could you please elaborate on this issue?

**Comment by AmanBisht01** [comment]
you need to add a chat feature to it but make sure that the chat must be room-specific eg. chat in one room should not appear in another room.

**Comment by AmanBisht01** [comment]
hope that helped ...

**Comment by sulogna2001** [comment]
Hey Can I work on this issue under GSSOC22

**Comment by AmanBisht01** [comment]
just work on this issue it will be  added to your GSSOC score .

**Comment by sulogna2001** [comment]
Sure I am working on it

**Comment by AmanBisht01** [comment]
@sulogna2001 
any update

**Comment by sulogna2001** [comment]
Working on it

**Comment by AmanBisht01** [comment]
ok
